restore fail job to workflow

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -11,10 +11,10 @@ jobs:
   echo-goodbye:
     runs-on: ubuntu-latest
     steps: 
-      - name: Major success
+      - name: Failed step
         run: |
-          echo "I will win"
-          exit 0
+          echo "I will fail"
+          exit 1
       - name: Say goodbye
         run: echo "Goodbye!"
 
